# Generated by Django 4.0.5 on 2022-07-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='web',
        ),
        migrations.AlterField(
            model_name='booking',
            name='lname',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
    ]
