# Generated by Django 4.0.5 on 2022-07-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_rename_email_address_booking_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='email',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='lname',
            new_name='last_name',
        ),
    ]
