# Generated by Django 4.0.5 on 2022-07-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_booking_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='last_name',
            new_name='lname',
        ),
    ]
